import request from 'supertest';
import fs from 'fs';
import path from 'path';
import { describe, it, expect, afterAll } from 'vitest';
import app from '../../app.js';
import { closeTestDb } from '../setup/testDb.js';

afterAll(async () => { await closeTestDb(); });

/**
 * The things a hosting platform needs from the app, and the config files that
 * tell it how to run.
 */
describe('health check', () => {
    it('answers without a session', async () => {
        const res = await request(app).get('/healthz');
        expect(res.status).toBe(200);
        expect(res.body.status).toBe('ok');
    });

    it('does not touch the database, so a slow query cannot fail the deploy', async () => {
        // If it queried anything, the response would carry data from it. It
        // reports only what the process itself knows.
        const res = await request(app).get('/healthz');
        expect(Object.keys(res.body).sort()).toEqual(['status', 'storage', 'uptime'].sort());
    });

    it('answers quickly enough for a health probe', async () => {
        const started = Date.now();
        await request(app).get('/healthz');
        expect(Date.now() - started).toBeLessThan(1000);
    });
});

describe('the config files a platform reads', () => {
    const root = process.cwd();

    it('declares a Node version, so the platform does not pick its own', () => {
        const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
        expect(pkg.engines?.node).toBeTruthy();
        expect(pkg.scripts.start).toBe('node app.js');
    });

    it('has a Render blueprint pointing at the health check and database storage', () => {
        const yaml = fs.readFileSync(path.join(root, 'render.yaml'), 'utf-8');
        expect(yaml).toContain('healthCheckPath: /healthz');
        // Render's disk is wiped on every deploy. Shipping a blueprint that
        // says FILE_STORAGE=disk would lose every upload.
        expect(yaml).toMatch(/key:\s*FILE_STORAGE[\s\S]{0,40}value:\s*database/);
        expect(yaml).toMatch(/key:\s*DB_SSL[\s\S]{0,40}value:\s*"true"/);
    });

    it('never commits a secret into the blueprint', () => {
        const yaml = fs.readFileSync(path.join(root, 'render.yaml'), 'utf-8');
        for (const key of ['DB_PASSWORD', 'GEMINI_API_KEY', 'GOOGLE_CLIENT_SECRET']) {
            const block = yaml.slice(yaml.indexOf(`key: ${key}`));
            expect(block.slice(0, 60)).toContain('sync: false');
        }
        // SESSION_SECRET must be generated by the platform and then LEFT ALONE -
        // a new value on each deploy would sign every user out.
        expect(yaml).toMatch(/key:\s*SESSION_SECRET[\s\S]{0,60}generateValue:\s*true/);
    });

    it('keeps .env and uploads out of the container image', () => {
        const ignore = fs.readFileSync(path.join(root, '.dockerignore'), 'utf-8');
        expect(ignore).toMatch(/^\.env$/m);
        expect(ignore).toMatch(/public\/uploads/);
        expect(ignore).toMatch(/^node_modules$/m);
    });

    it('runs the container as a non-root user', () => {
        const dockerfile = fs.readFileSync(path.join(root, 'Dockerfile'), 'utf-8');
        expect(dockerfile).toMatch(/^USER node$/m);
        expect(dockerfile).toMatch(/npm ci --omit=dev/);
        expect(dockerfile).toMatch(/HEALTHCHECK/);
    });
});
